name: CI
on: [ push ]

env:
  CI: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.0", "3.1", "3.2", "3.3"]
        activesupport-version: ["activesupport-6.1", "activesupport-7.1"]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bin/setup
      - run: bundle exec appraisal generate
      - run: bundle exec appraisal install
      - run: bundle exec appraisal ${{ matrix.activesupport-version }} bin/test
